-- 코드를 입력하세요
-- SELECT MONTH(DATE_OF_BIRTH) FROM MEMBER_PROFILE

SELECT MEMBER_ID,MEMBER_NAME,GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH FROM MEMBER_PROFILE WHERE MONTH(DATE_OF_BIRTH)=3 and GENDER = 'W' and TLNO is NOT NULL order by MEMBER_ID 